# Generated by Django 4.1.2 on 2023-09-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("profiles", "0003_author_facebook_author_instagram_author_linkedin_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=30, null=True)),
                (
                    "img",
                    models.ImageField(blank=True, null=True, upload_to="media/posts"),
                ),
                ("date", models.DateField()),
                ("place", models.CharField(blank=True, max_length=30, null=True)),
                ("participants", models.ManyToManyField(to="profiles.author")),
            ],
        ),
    ]
