# Generated by Django 4.1.2 on 2023-09-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=30, null=True)),
                ("about", models.TextField()),
                (
                    "img",
                    models.FileField(blank=True, null=True, upload_to="media/profiles"),
                ),
            ],
        ),
    ]
