# Generated by Django 4.1.2 on 2023-09-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="media/profiles"),
        ),
    ]
